[package]
name = "stmc_rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.46"
ndarray = "0.16.1"
plotters = "0.3.7"
